version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "[ %(asctime)s ] %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "[ %(asctime)s ] %(levelname)s - %(name)s - %(filename)s:%(lineno)d - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout

  rotating_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log  # This will be overridden in Python
    maxBytes: 5242880
    backupCount: 3

root:
  level: DEBUG
  handlers: [console_handler, rotating_file_handler]
