columns:
- _id: string
- Pregnancies: int
- Glucose: float
- BloodPressure: int
- SkinThickness: int
- Insulin: int
- BMI: float
- DiabetesPedigreeFunction: float
- Age: int
- Outcome: int

numerical_columns:
- Pregnancies
- Glucose
- BloodPressure
- SkinThickness
- Insulin
- BMI
- DiabetesPedigreeFunction
- Age

categorical_columns:
- Outcome

drop_columns:
- _id

# for data transformation
num_features:
- Pregnancies
- Glucose
- BloodPressure
- SkinThickness
- Insulin
- BMI
- DiabetesPedigreeFunction
- Age

mm_columns: []
